function [ret] = snp_persistent(doch,event)
%%
%
%  file:   snp_persistent.m
%  author: Polcz Péter <ppolcz@gmail.com>
%
%  Created on 2016.01.31. Sunday, 15:08:42
%

cmd = sprintf([ ...
    'try c = evalin(''caller'',''persist''); catch; c = []; end\n' ...
    'persist = Persist(mfilename(''fullpath''), c); clear c; \n' ...
    'persist.backup();\n' ...
    '%%clear persist']);

% cmd = sprintf([ '\n' ...
%     '%% fname: full path of the actual file\n' ...
%     'pcz_cmd_fname(''fname''); stack = dbstack;\n' ...
%     'if ~ismember(''publish'', {stack.name}), persist = pcz_persist(fname); end\n' ...
%     '%%persist.backup();\n' ...
%     '%%clear persist\n']);

if nargout > 0
    ret = cmd;
else
    % Java objects concerning the active document and the editor
    active = matlab.desktop.editor.getActive;
    editor = active.JavaEditor;
    editor.insertTextAtCaret(cmd);
end

% ret = sprintf([ '\n' ...
%     '%% fname = full path of the actual file\n' ...
%     'eval(pcz_cmd_fname(''fname''));\n' ...
%     '\n' ...
%     '%% global variables\nG__ = pglobals;\n' ...
%     '\n' ...
%     '%% cache directory for the mat files\n' ...
%     'persist_bin_dir = proot(fname,G__.RELPATH_MAT_FILES);\n' ...
%     '\n' ...
%     '%% cache directory for the figures\n' ...
%     'persist_fig_dir = proot(fname,G__.RELPATH_FIGURES);\n' ...
%     '\n' ...
%     ]);

clipboard('copy', 'persist.stoplog;');


end